packaging_format = 2
id = "hisyeo-discord-bot"
name = "Hîsyêô Discord Bot"
description = "A Discord bot for the Hîsyêô language"
maintainers = "MadcapJake"
version = "0.1.0"

[upstream]
license = "MIT"
website = "https://hisyeo.github.io"
code = "https://github.com/Hisyeo/DiscordBot"

[integration]
yunohost = ">= 4.0.0"
multi_instance = false
services = [ "nginx" ]

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/bot"

    [install.with_sftp]
    ask.en = "Do you need a SFTP access?"
    ask.fr = "Avez-vous besoin d'un accès SFTP ?"
    type = "boolean"
    default = true

    [install.password]
    type = "password"
    optional = true
    help.en = "Optional, this corresponds to the password for SFTP access, if you enabled it"
    help.fr = "Optionnel, corresponds au mot de passe pour l'accès SFTP, si vous l'avez activé"

    [install.init_main_permissions]
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/" # WHAT DOES THIS DO?

    [resources.nodejs]
    version = "24.11.1"
