#!/bin/bash

source /usr/share/yunohost/helpers



# Get the arguments
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
user=$YNH_APP_ARG_USER
password=$YNH_APP_ARG_PASSWORD
app_name=$YNH_APP_INSTANCE_NAME
app_repo=$YNH_APP_ARG_APP_REPO
app_branch=$YNH_APP_ARG_APP_BRANCH
app_commit=$YNH_APP_ARG_APP_COMMIT
app_launch_command=$YNH_APP_ARG_APP_LAUNCH_COMMAND
app_port=$YNH_APP_ARG_APP_PORT
is_public=$YNH_APP_ARG_IS_PUBLIC

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_script_progression --message="Validating installation parameters..." --weight=2

[ $with_sftp -eq 0 ] || [ "$password" != "" ] || ynh_die --message="You need to set a password to enable SFTP"

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..." --weight=1

ynh_app_setting_set --app=$app --key=password --value=$password

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=2

nginx_extra_conf_dir="/etc/nginx/conf.d/$domain.d/$app.d"
mkdir -p "$nginx_extra_conf_dir"

# Create a dedicated NGINX config
ynh_add_nginx_config
ynh_add_config --template="custom-nginx-config.conf" --destination="$nginx_extra_conf_dir/custom.conf"

# Make the app public
if [ "$is_public" = "true" ]; then
    sudo yunohost app permission $app_name --add "main" --allow "visitors"
fi

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression --message="Configuring system user..."

if [ $with_sftp -eq 1 ]
then
    groups="sftp.app"
else
    groups=""
fi

    ynh_system_user_create --username=$app --home_dir="$install_dir" --groups="$groups"

if [ $with_sftp -eq 1 ]
then
    # Add the password to this user
    chpasswd <<< "${app}:${password}"
fi

#=================================================
# INSTALL THE APP
#=================================================
ynh_script_progression --message="Running installation..." --weight=3

# Clone the repository
if [ -n "$app_repo" ]; then
    sudo git clone $app_repo $install_dir
    if [ -n "$app_branch" ]; then
        sudo git -C $install_dir checkout $app_branch
    fi
    if [ -n "$app_commit" ]; then
        sudo git -C $install_dir checkout $app_commit
    fi
else
    # If no repo is provided, we assume the head of the Hisyeo bot main branch
    sudo git clone https://github.com/Hisyeo/DiscordBot.git $install_dir
fi

# Set the owner of the app
sudo chown -R $user:$user $install_dir

# Install the dependencies
if [ -f "$install_dir/package.json" ]; then
    sudo yunohost app shell $app_name --script "cd $install_dir && npm install"
fi

#=================================================
# SYSTEMD CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring SystemD service..." --weight=2

# Guess the launch command
if [ -z "$app_launch_command" ]; then
    if [ -f "$install_dir/package.json" ]; then
        app_launch_command=$(sudo yunohost app shell $app_name --script "cd $install_dir && jq -r .scripts.start package.json")
    fi
fi

# Guess the port
if [ -z "$app_port" ]; then
    if [ -f "$install_dir/app.js" ]; then
        app_port=$(sudo yunohost app shell $app_name --script "cd $install_dir && grep -oP 'process.env.PORT || \K[0-9]+' app.js")
    fi
fi

ynh_config_add_systemd

#=================================================
# START THE APP
#=================================================
ynh_script_progression --message="Starting SystemD service..." --weight=1

# Start the service
sudo yunohost app service $app_name start

ynh_script_progression --message="Reloading NGINX..." --weight=1

# Reload nginx
sudo yunohost service reload nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
