#!/bin/bash

# Get the arguments
user=$YNH_APP_ARG_USER
app_name=$YNH_APP_INSTANCE_NAME
app_repo=$YNH_APP_ARG_APP_REPO
app_branch=$YNH_APP_ARG_APP_BRANCH
app_commit=$YNH_APP_ARG_APP_COMMIT

#=================================================
# UPGRADE THE APP
#=================================================

# Update the repository
if [ -n "$app_repo" ]; then
    sudo git -C $install_dir pull
    if [ -n "$app_branch" ]; then
        sudo git -C $install_dir checkout $app_branch
    fi
    if [ -n "$app_commit" ]; then
        sudo git -C $install_dir checkout $app_commit
    fi
else
    # If no repo is provided, we assume the head of the Hisyeo bot main branch
    sudo git clone https://github.com/Hisyeo/DiscordBot.git $install_dir
fi

# Set the owner of the app
sudo chown -R $user:$user $install_dir

# Install the dependencies
if [ -f "$install_dir/package.json" ]; then
    sudo yunohost app shell $app_name --script "cd $install_dir && npm install"
fi

#=================================================
# RESTART THE APP
#=================================================

# Restart the service
sudo yunohost app service $app_name restart
