#!/bin/bash

#=================================================
# SCRIPT FOR MY_WEBAPP
#
# This script is a helper to upgrade a web application.
#
# It will update the application from the git repository.
#
# The script is intended to be used with the my_webapp package for YunoHost.
#
# Usage: sudo yunohost app upgrade my_webapp
#
#=================================================

#=================================================
# SET ALL THE THINGS
#=================================================

# Exit on error
set -e

# Get the arguments
user=$YNH_APP_ARG_USER
app_name=$YNH_APP_INSTANCE_NAME
app_repo=$YNH_APP_ARG_APP_REPO
app_branch=$YNH_APP_ARG_APP_BRANCH
app_commit=$YNH_APP_ARG_APP_COMMIT

# Set the home of the user
user_home="/home/$user"

# Set the final path of the app
final_path="$user_home/www"

#=================================================
# UPGRADE THE APP
#=================================================

# Update the repository
if [ -n "$app_repo" ]; then
    sudo git -C $final_path pull
    if [ -n "$app_branch" ]; then
        sudo git -C $final_path checkout $app_branch
    fi
    if [ -n "$app_commit" ]; then
        sudo git -C $final_path checkout $app_commit
    fi
else
    # If no repo is provided, we copy the content of the current directory
    sudo cp -r . $final_path
fi

# Set the owner of the app
sudo chown -R $user:$user $final_path

# Install the dependencies
if [ -f "$final_path/package.json" ]; then
    sudo yunohost app shell $app_name --script "cd $final_path && npm install"
fi

#=================================================
# RESTART THE APP
#=================================================

# Restart the service
sudo yunohost app service $app_name restart
